### PR TITLE
Add postcss-extend

### PR DESCRIPTION
**Pull request by crhallberg**
Adding [postcss-extend](https://github.com/travco/postcss-extend) would allow users to combine tachyons to build their own custom classes.

For example, if you add the css on the left to `_styles.css` in tachyons/src, you could get the pretty buttons on the right with just one class.

| oooooo | aaaaah |
|--|--|
| image | image |

Unfortunately, I don't see any places in the core tachyons where this would be helpful.

### CODE REVIEW

**Comment by crhallberg** [comment]
Actually, one place that may benefit from this, at least size-wise: skin-pseudos.

```css
.white { color: var(--white); }
.hover-white:hover,
.hover-white:focus { color: var(--white); }
```
creates
```css
.white { color: #fff; }
.hover-white:hover,
.hover-white:focus { color: #fff; }
```
---
meanwhile
```css
.white { color: var(--white); }
.hover-white:hover,
.hover-white:focus { @extend .white; }
```
would create
```css
.white,
.hover-white:hover,
.hover-white:focus { color: #fff; }
```

**Comment by crhallberg** [comment]
Finally got test results, reduces min (non gzip) size by 2,400 bytes.

image

**Comment by crhallberg** [comment]
I just realized my screenshot above is working off a branch of [`postcss-extend`](https://github.com/travco/postcss-extend/pull/27). The below code does the same thing, but is more verbose, if you wanted to test.
```css
.button {
  @extend .border-box;
  @extend .dib;
  @extend .ma1;
  @extend .ph3;
  @extend .pv1;
  @extend .ba;
  @extend .bw2;
  @extend .b--navy;
  @extend .hover-b--blue;
  @extend .f6;
  @extend .b;
  @extend .tracked;
  @extend .white;
  @extend .bg-dark-blue;
  @extend .hover-bg-blue;
  @extend .br2;
  @extend .pointer;
  @extend .no-underline;
}
```

**Comment by johno** [comment]
Thanks for the PR!

Long story short, we don't want to directly advocate for using `extend` as we think it is a bit of an anti-pattern (something that is a blog post in and of itself). However, we would like to expose the ability to use postcss-extend, or any other plugin through our build tooling.

If you'd like (or I can if you don't have the time), we could amend this PR to make tachyons-build-css accept an optional array of plugins if that makes sense? That way postcss-extend, and any other plugin a user would like to leverage can be optionally added to the postcss build system.

**Comment by crhallberg** [comment]
That does make sense, I'll see what I can do!

**Comment by crhallberg** [comment]
Having looked into this a little more, I think most users who want to extend or build upon tachyons would include the [src folder](https://github.com/tachyons-css/tachyons/tree/master/src) from the tachyons repository into their own build system.

I agree with your decision to not combine selectors using extend (more modular, easier to understand), it's an excellent call. If you still want me to look into adding an optional array for more build tools, let me know.

**Comment by johno** [comment]
Thanks for looking into it! I just added an issue to remind me. I think it's still something we'd like to support eventually, but it's more of a "nice to have".

Yeah, it seems like those that currently desire custom builds handle it themselves so it hasn't been a high priority as a result.

**Pull request closed without merging**
